Bug fix BGDIINF_SB-1690: raise error on invalid query parameters
geoadmin/service-stac pull request #242
Opened 2021-03-02 05:37 UTC by hansmannj

The `collections` and `items` endpoints currently did not return errors on GET requests containing invalid parameters, e.g. on
https://service-stac.dev.bgdi.ch/api/stac/v0.9/collections/ch.swisstopo.swissbuildings3d_2/items?limit=50&random_nonsense_parameter=blablablubb
This fix now raises a ValidationError in case invalid query parameters are found.

2021-03-02 06:11 UTC, ltshb requested changes
I would not add such validator, for the following reasons:
1. From an architecture point of view, validation is done either in the model, or in the serializer or in the manager (queryset). We don't have any validation at the view level
2. In the validation functions, the query are copied, which is not very efficient
3. I would differentiate between query parameter with invalid value, which should return an error and invalida parameter (e.g. `foo=bar`). In the second case most of the API are just ignoring such parameters, they could even be simply blocked by the CDN like Cloudfront which might not forward unknown query parameter.
4. Because invalid query parameter (`foo=bar`) are not whitelisted in CF we might have different behavior when the request is handled from cache or from origin.
I would revert and leave it as it is, doing nothing if providing unknown parameter is not too bad in my opinion, I first thought it was a bug because we were giving a correct parameter with incorrect value. But in this case the Items and Collections endpoint don't have any parameter.

2021-03-02 07:56 UTC, hansmannj commented
> I would not add such validator, for the following reasons:
> 
>     1. From an architecture point of view, validation is done either in the model, or in the serializer or in the manager (queryset). We don't have any validation at the view level
> 
>     2. In the validation functions, the query are copied, which is not very efficient
> 
>     3. I would differentiate between query parameter with invalid value, which should return an error and invalida parameter (e.g. `foo=bar`). In the second case most of the API are just ignoring such parameters, they could even be simply blocked by the CDN like Cloudfront which might not forward unknown query parameter.
> 
>     4. Because invalid query parameter (`foo=bar`) are not whitelisted in CF we might have different behavior when the request is handled from cache or from origin.
>        I would revert and leave it as it is, doing nothing if providing unknown parameter is not too bad in my opinion, I first thought it was a bug because we were giving a correct parameter with incorrect value. But in this case the Items and Collections endpoint don't have any parameter.

To 1: I implemented the validation in analogy to the SearchListView's validation. That's why its in the view level, but I could also move that elsewhere.

To 3: Invalid values are already handled, this is only about invalid parameters. Simply ignoring could be an option, but I thought, it would be "nice" of us, to return an error instead. E.g. when someone has a spell error when trying to filter e.f. for `datime` instead of `datetime`. In this case simply the first 100 items of all collections will be returned, instead of an error. The user gets data but the data doesn't match the filter he applied. If he's lucky, the user will notice that by himself. Otherwise he'll work with wrong data.. That's why I would opt for returning an error rather than ignoring and just returning "something".

2021-03-02 12:16 UTC, IsabelleBzr reviewed
I agree with the comment Jürgen made. It would be "nice" of us to send an error message. We are already doing that in search, why also not expand for the collections and items endpoint

2021-03-02 12:35 UTC, ltshb commented
The issue that I see is with CloudFront caching, looking with these examples below:

1. GET /collections?no_limit=50 => return HTTP 400 and the result is cached by CF under the key `GET /collections`
2. GET /collections => return 400 from cached answer above

Other example

1. GET /collections => return HTTP 200, and the result is cached by CF under the key `GET /collections`
2. GET /collections?no_limit=50 => return 200 from cached answer above.

So if you want to correctly return an error with invalid/unknown query parameter without issue with caching, we need to change the CF caching configuration to cache every query parameters, which will reduce the CF caching performance and cache Hit ratio. I agree that this PR would be nice for the user but it will have impact on the performance and therefore it is in my opinion not worth it. @boecklic and @sontags what are your opinion ?

2021-03-04 08:25 UTC, ltshb commented
The cache issue already on prod ! See https://jira.swisstopo.ch/browse/BGDIINF_SB-1700

2021-03-05 08:18 UTC, hansmannj commented
After discussions in the service-stac DEV team, it was decided to not implement this PR, hence I will close this now.
Implementation would negatively influence caching performance/behaviour and also potentially open DOS vectors.

2021-03-05 08:18 UTC, closed without merging