serializer with polygon
geoadmin/service-stac pull request #72
Opened 2020-11-06 10:26 UTC by rebert

2020-11-06 10:27 UTC, rebert commented
@hansmannj für ein sauberes migrations hat es nicht gereicht

2020-11-06 15:12 UTC, hansmannj commented
This should work now, thanks for your work on that @rebert 
Probably there should be some more unit tests on it (in another PR).
And there is an issue, that the calculated bbox from the code differs from the expected one in the sample item, from which the geometry was copied. But I think, this might as well be an error in the sample data. To be checked on Monday.

2020-11-09 06:01 UTC, ltshb requested changes

2020-11-09 06:17 UTC, ltshb commented
What happened with the migration files ? Why do you change existing ? Why there is two migration starting with 0017 ?

2020-11-09 06:52 UTC, ltshb commented
Before merging, we need to first wait on PR #73 and #74 to be merged. Then recreate the migrations file for this PR.

2020-11-09 06:55 UTC, rebert commented on app/stac_api/serializers.py
> +            ret["bbox"] = {"bbox": [[bbox]]}
In theory we will never need to try except this... it is more to have a easier live when developing... when deleting the bbox of a item by purpose in the db

2020-11-09 10:02 UTC, ltshb commented on app/stac_api/models.py
> +    extent_geometry = models.PolygonField(default=None, srid=4326, editable=True, null=True)
This extent_geometry should not be editable by the user and it should be `blank=True` otherwise it is added to the admin page.

2020-11-09 13:06 UTC, ltshb approved these changes
:+1:

2020-11-09 13:15 UTC, rebert commented
@hansmannj thanks for your support.

2020-11-09 13:16 UTC, merged