BGDIINF_SB-1409: corrected wrong link in samples
geoadmin/service-stac pull request #87
Opened 2020-11-12 19:35 UTC by ltshb

2020-11-13 08:22 UTC, rebert approved these changes
populate_db and lint worked fine and the user experience via /admin as well

2020-11-16 09:21 UTC, boecklic requested changes
Nice! One comment about content in `__init__.py`

2020-11-16 09:21 UTC, boecklic commented on app/tests/__init__.py
> +
I'd move the content in this file to a dedicated file, like `basetest.py` or `common.py` or sth like this...

2020-11-16 09:59 UTC, boecklic approved these changes

2020-11-16 10:22 UTC, merged