BGDIINF_SB-1382 made admin page also accessible under API_BASE path/admin/
geoadmin/service-stac pull request #89
Opened 2020-11-12 20:59 UTC by hansmannj

2020-11-13 08:29 UTC, rebert requested changes
It works fine. But when running the make serve, I get the warning:
?: (urls.W005) URL namespace 'admin' isn't unique. You may not be able to reverse all URLs in this namespace

not sure if it has to be fixed:
https://stackoverflow.com/questions/53473027/django-warning-urls-w005-url-namespace-isnt-unique

2020-11-13 09:37 UTC, hansmannj commented
Thanks @rebert 
Yeah, I am also not sure, if this is exactly what was asked for in BGDIINF_SB-1382 yet.
I'll have a look at it

2020-11-16 09:44 UTC, boecklic approved these changes

2020-11-16 10:57 UTC, rebert approved these changes
lgtm

2020-11-16 12:00 UTC, merged